### ISSUE TITLE
Add app requirements to README.md

### ISSUE THREAD

**Issue by tkasu** [maspalio/app-mook#1]
As this repository is used in mooc and other people are reviewing it, requirements section in README.md would be nice for non Perl users. For example:

## Requirements

* Perl X.X.X (?)
*  cpanm? (I'm failing in this part)

For reference, just cloning the repository and running ./bin/deps.sh will results following in macOS Sierra:

```
./bin/deps.sh: line 6: cpanm: command not found
```

**Comment by maspalio** [comment]
Sure, will do it. Thank you for reporting this. Perl is any "modern" version, i.e., post-5.10.1. About `cpanm`, `cpanminus` package is to be installed on a debian/ubuntu box for example (requires root privileges).

**Comment by maspalio** [comment]
Done, many thanks again! ;^)

**Comment by maspalio** [comment]
I am using a macOS box too. I recommend [MacPorts](https://www.macports.org/) to handle what is not handled via AppStore. `cpanminus` package name within MacPorts environment is `p5.24-app-cpanminus`.

**Comment by tkasu** [comment]
Works with the added instructions, thanks!

**Comment by maspalio** [comment]
You are welcome! ;^)
